version: '3.8'

services:
  service_name:
    image: z3r0xf/selfhostscreenshot:latest
    ports:
      - "7070:7070"
    environment:
      - API_KEY=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX
      - DELETE_TIME_MINUTES=1
